const products = [
  {
    id: 1,
    name: "Gorgeous Aluminum Bacon",
    price: 301.5,
    image: "https://loremflickr.com/400/300/vegetable?random=1",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 2,
    name: "Tasty Marble Gloves",
    price: 664.9,
    image: "https://loremflickr.com/400/300/vegetable?random=2",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 3,
    name: "Ergonomic Steel Towels",
    price: 390.49,
    image: "https://loremflickr.com/400/300/vegetable?random=3",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 4,
    name: "Bespoke Bronze Tuna",
    price: 434.49,
    image: "https://loremflickr.com/400/300/fruit?random=4",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 5,
    name: "Modern Wooden Fish",
    price: 665.15,
    image: "https://loremflickr.com/400/300/fruit?random=5",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 6,
    name: "Awesome Metal Ball",
    price: 207.75,
    image: "https://loremflickr.com/400/300/fruit?random=6",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 7,
    name: "Bespoke Ceramic Chair",
    price: 906.45,
    image: "https://loremflickr.com/400/300/fruit?random=7",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 8,
    name: "Handcrafted Plastic Ball",
    price: 182.59,
    image: "https://loremflickr.com/400/300/seed?random=8",
    currency: "₹",
    category: "seed",
  },
  {
    id: 9,
    name: "Electronic Silk Car",
    price: 494.49,
    image: "https://loremflickr.com/400/300/fruit?random=9",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 10,
    name: "Handmade Silk Cheese",
    price: 232.75,
    image: "https://loremflickr.com/400/300/seed?random=10",
    currency: "₹",
    category: "seed",
  },
  {
    id: 11,
    name: "Intelligent Silk Soap",
    price: 635.25,
    image: "https://loremflickr.com/400/300/seed?random=11",
    currency: "₹",
    category: "seed",
  },
  {
    id: 12,
    name: "Oriental Granite Shoes",
    price: 542.49,
    image: "https://loremflickr.com/400/300/vegetable?random=12",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 13,
    name: "Oriental Rubber Keyboard",
    price: 316.79,
    image: "https://loremflickr.com/400/300/fruit?random=13",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 14,
    name: "Handcrafted Gold Shoes",
    price: 264.6,
    image: "https://loremflickr.com/400/300/fruit?random=14",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 15,
    name: "Generic Bamboo Salad",
    price: 471.83,
    image: "https://loremflickr.com/400/300/fruit?random=15",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 16,
    name: "Unbranded Wooden Fish",
    price: 842.39,
    image: "https://loremflickr.com/400/300/fruit?random=16",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 17,
    name: "Refined Gold Shoes",
    price: 88.09,
    image: "https://loremflickr.com/400/300/fruit?random=17",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 18,
    name: "Handcrafted Marble Salad",
    price: 507.89,
    image: "https://loremflickr.com/400/300/seed?random=18",
    currency: "₹",
    category: "seed",
  },
  {
    id: 19,
    name: "Licensed Ceramic Sausages",
    price: 153.89,
    image: "https://loremflickr.com/400/300/fruit?random=19",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 20,
    name: "Incredible Ceramic Shoes",
    price: 338.19,
    image: "https://loremflickr.com/400/300/seed?random=20",
    currency: "₹",
    category: "seed",
  },
  {
    id: 21,
    name: "Awesome Ceramic Computer",
    price: 181.45,
    image: "https://loremflickr.com/400/300/vegetable?random=21",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 22,
    name: "Practical Gold Table",
    price: 354.49,
    image: "https://loremflickr.com/400/300/fruit?random=22",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 23,
    name: "Luxurious Marble Computer",
    price: 262.29,
    image: "https://loremflickr.com/400/300/fruit?random=23",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 24,
    name: "Soft Metal Bike",
    price: 418.25,
    image: "https://loremflickr.com/400/300/fruit?random=24",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 25,
    name: "Gorgeous Marble Cheese",
    price: 822.4,
    image: "https://loremflickr.com/400/300/seed?random=25",
    currency: "₹",
    category: "seed",
  },
  {
    id: 26,
    name: "Handcrafted Silk Pizza",
    price: 941.77,
    image: "https://loremflickr.com/400/300/vegetable?random=26",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 27,
    name: "Soft Plastic Shirt",
    price: 423.05,
    image: "https://loremflickr.com/400/300/vegetable?random=27",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 28,
    name: "Electronic Bronze Ball",
    price: 469.06,
    image: "https://loremflickr.com/400/300/vegetable?random=28",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 29,
    name: "Bespoke Silk Chair",
    price: 412.09,
    image: "https://loremflickr.com/400/300/seed?random=29",
    currency: "₹",
    category: "seed",
  },
  {
    id: 30,
    name: "Recycled Gold Bacon",
    price: 701.05,
    image: "https://loremflickr.com/400/300/fruit?random=30",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 31,
    name: "Tasty Gold Cheese",
    price: 940.29,
    image: "https://loremflickr.com/400/300/vegetable?random=31",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 32,
    name: "Rustic Gold Sausages",
    price: 576.19,
    image: "https://loremflickr.com/400/300/vegetable?random=32",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 33,
    name: "Electronic Ceramic Computer",
    price: 494.39,
    image: "https://loremflickr.com/400/300/vegetable?random=33",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 34,
    name: "Sleek Plastic Sausages",
    price: 976.69,
    image: "https://loremflickr.com/400/300/fruit?random=34",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 35,
    name: "Elegant Wooden Mouse",
    price: 34.49,
    image: "https://loremflickr.com/400/300/vegetable?random=35",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 36,
    name: "Bespoke Steel Car",
    price: 927.02,
    image: "https://loremflickr.com/400/300/seed?random=36",
    currency: "₹",
    category: "seed",
  },
  {
    id: 37,
    name: "Luxurious Granite Shirt",
    price: 924.75,
    image: "https://loremflickr.com/400/300/seed?random=37",
    currency: "₹",
    category: "seed",
  },
  {
    id: 38,
    name: "Intelligent Wooden Keyboard",
    price: 630.61,
    image: "https://loremflickr.com/400/300/vegetable?random=38",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 39,
    name: "Awesome Metal Salad",
    price: 105.44,
    image: "https://loremflickr.com/400/300/seed?random=39",
    currency: "₹",
    category: "seed",
  },
  {
    id: 40,
    name: "Rustic Bronze Sausages",
    price: 156.19,
    image: "https://loremflickr.com/400/300/seed?random=40",
    currency: "₹",
    category: "seed",
  },
  {
    id: 41,
    name: "Handcrafted Silk Pizza",
    price: 507.29,
    image: "https://loremflickr.com/400/300/fruit?random=41",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 42,
    name: "Intelligent Bamboo Pants",
    price: 113.35,
    image: "https://loremflickr.com/400/300/fruit?random=42",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 43,
    name: "Modern Cotton Computer",
    price: 397.85,
    image: "https://loremflickr.com/400/300/fruit?random=43",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 44,
    name: "Ergonomic Steel Car",
    price: 674.6,
    image: "https://loremflickr.com/400/300/seed?random=44",
    currency: "₹",
    category: "seed",
  },
  {
    id: 45,
    name: "Handmade Metal Fish",
    price: 46.65,
    image: "https://loremflickr.com/400/300/seed?random=45",
    currency: "₹",
    category: "seed",
  },
  {
    id: 46,
    name: "Intelligent Plastic Keyboard",
    price: 130.29,
    image: "https://loremflickr.com/400/300/fruit?random=46",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 47,
    name: "Soft Bamboo Gloves",
    price: 138.89,
    image: "https://loremflickr.com/400/300/vegetable?random=47",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 48,
    name: "Tasty Gold Tuna",
    price: 267.95,
    image: "https://loremflickr.com/400/300/seed?random=48",
    currency: "₹",
    category: "seed",
  },
  {
    id: 49,
    name: "Oriental Marble Salad",
    price: 352.35,
    image: "https://loremflickr.com/400/300/fruit?random=49",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 50,
    name: "Elegant Rubber Pizza",
    price: 376.19,
    image: "https://loremflickr.com/400/300/vegetable?random=50",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 51,
    name: "Gorgeous Ceramic Chicken",
    price: 721.25,
    image: "https://loremflickr.com/400/300/seed?random=51",
    currency: "₹",
    category: "seed",
  },
  {
    id: 52,
    name: "Oriental Silk Mouse",
    price: 493.69,
    image: "https://loremflickr.com/400/300/seed?random=52",
    currency: "₹",
    category: "seed",
  },
  {
    id: 53,
    name: "Luxurious Marble Chicken",
    price: 881.39,
    image: "https://loremflickr.com/400/300/seed?random=53",
    currency: "₹",
    category: "seed",
  },
  {
    id: 54,
    name: "Tasty Steel Tuna",
    price: 871.89,
    image: "https://loremflickr.com/400/300/vegetable?random=54",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 55,
    name: "Sleek Ceramic Sausages",
    price: 737.29,
    image: "https://loremflickr.com/400/300/fruit?random=55",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 56,
    name: "Intelligent Marble Chair",
    price: 205.99,
    image: "https://loremflickr.com/400/300/seed?random=56",
    currency: "₹",
    category: "seed",
  },
  {
    id: 57,
    name: "Refined Ceramic Keyboard",
    price: 391.49,
    image: "https://loremflickr.com/400/300/vegetable?random=57",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 58,
    name: "Elegant Bronze Pizza",
    price: 136.15,
    image: "https://loremflickr.com/400/300/vegetable?random=58",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 59,
    name: "Unbranded Silk Pants",
    price: 1.19,
    image: "https://loremflickr.com/400/300/seed?random=59",
    currency: "₹",
    category: "seed",
  },
  {
    id: 60,
    name: "Small Bamboo Mouse",
    price: 564.09,
    image: "https://loremflickr.com/400/300/vegetable?random=60",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 61,
    name: "Frozen Metal Hat",
    price: 126.69,
    image: "https://loremflickr.com/400/300/seed?random=61",
    currency: "₹",
    category: "seed",
  },
  {
    id: 62,
    name: "Bespoke Ceramic Mouse",
    price: 218.49,
    image: "https://loremflickr.com/400/300/fruit?random=62",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 63,
    name: "Refined Cotton Keyboard",
    price: 611.69,
    image: "https://loremflickr.com/400/300/seed?random=63",
    currency: "₹",
    category: "seed",
  },
  {
    id: 64,
    name: "Fantastic Aluminum Fish",
    price: 102.35,
    image: "https://loremflickr.com/400/300/fruit?random=64",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 65,
    name: "Handcrafted Aluminum Soap",
    price: 103.79,
    image: "https://loremflickr.com/400/300/vegetable?random=65",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 66,
    name: "Generic Marble Chips",
    price: 561.95,
    image: "https://loremflickr.com/400/300/seed?random=66",
    currency: "₹",
    category: "seed",
  },
  {
    id: 67,
    name: "Tasty Metal Towels",
    price: 182.29,
    image: "https://loremflickr.com/400/300/fruit?random=67",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 68,
    name: "Soft Metal Pants",
    price: 456.59,
    image: "https://loremflickr.com/400/300/seed?random=68",
    currency: "₹",
    category: "seed",
  },
  {
    id: 69,
    name: "Frozen Silk Chicken",
    price: 331.49,
    image: "https://loremflickr.com/400/300/fruit?random=69",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 70,
    name: "Small Gold Hat",
    price: 370.99,
    image: "https://loremflickr.com/400/300/seed?random=70",
    currency: "₹",
    category: "seed",
  },
  {
    id: 71,
    name: "Luxurious Plastic Chips",
    price: 380.09,
    image: "https://loremflickr.com/400/300/vegetable?random=71",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 72,
    name: "Handmade Rubber Chair",
    price: 297.79,
    image: "https://loremflickr.com/400/300/seed?random=72",
    currency: "₹",
    category: "seed",
  },
  {
    id: 73,
    name: "Modern Concrete Tuna",
    price: 537.79,
    image: "https://loremflickr.com/400/300/seed?random=73",
    currency: "₹",
    category: "seed",
  },
  {
    id: 74,
    name: "Licensed Bamboo Fish",
    price: 517.49,
    image: "https://loremflickr.com/400/300/fruit?random=74",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 75,
    name: "Gorgeous Bamboo Keyboard",
    price: 15.69,
    image: "https://loremflickr.com/400/300/seed?random=75",
    currency: "₹",
    category: "seed",
  },
  {
    id: 76,
    name: "Luxurious Marble Chair",
    price: 357.77,
    image: "https://loremflickr.com/400/300/seed?random=76",
    currency: "₹",
    category: "seed",
  },
  {
    id: 77,
    name: "Rustic Ceramic Salad",
    price: 581.79,
    image: "https://loremflickr.com/400/300/seed?random=77",
    currency: "₹",
    category: "seed",
  },
  {
    id: 78,
    name: "Licensed Cotton Gloves",
    price: 510.8,
    image: "https://loremflickr.com/400/300/vegetable?random=78",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 79,
    name: "Luxurious Ceramic Computer",
    price: 956.15,
    image: "https://loremflickr.com/400/300/fruit?random=79",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 80,
    name: "Elegant Cotton Salad",
    price: 107.89,
    image: "https://loremflickr.com/400/300/fruit?random=80",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 81,
    name: "Elegant Marble Shirt",
    price: 776.39,
    image: "https://loremflickr.com/400/300/vegetable?random=81",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 82,
    name: "Generic Wooden Sausages",
    price: 199.07,
    image: "https://loremflickr.com/400/300/seed?random=82",
    currency: "₹",
    category: "seed",
  },
  {
    id: 83,
    name: "Fresh Wooden Chair",
    price: 201.49,
    image: "https://loremflickr.com/400/300/fruit?random=83",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 84,
    name: "Oriental Cotton Soap",
    price: 366.76,
    image: "https://loremflickr.com/400/300/seed?random=84",
    currency: "₹",
    category: "seed",
  },
  {
    id: 85,
    name: "Refined Marble Fish",
    price: 413.99,
    image: "https://loremflickr.com/400/300/fruit?random=85",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 86,
    name: "Handcrafted Ceramic Shoes",
    price: 443.59,
    image: "https://loremflickr.com/400/300/seed?random=86",
    currency: "₹",
    category: "seed",
  },
  {
    id: 87,
    name: "Frozen Aluminum Towels",
    price: 882.19,
    image: "https://loremflickr.com/400/300/seed?random=87",
    currency: "₹",
    category: "seed",
  },
  {
    id: 88,
    name: "Electronic Plastic Tuna",
    price: 27.65,
    image: "https://loremflickr.com/400/300/vegetable?random=88",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 89,
    name: "Unbranded Steel Bike",
    price: 16.39,
    image: "https://loremflickr.com/400/300/vegetable?random=89",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 90,
    name: "Sleek Marble Shirt",
    price: 936.09,
    image: "https://loremflickr.com/400/300/fruit?random=90",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 91,
    name: "Incredible Bamboo Sausages",
    price: 216.35,
    image: "https://loremflickr.com/400/300/fruit?random=91",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 92,
    name: "Gorgeous Gold Chicken",
    price: 639.09,
    image: "https://loremflickr.com/400/300/vegetable?random=92",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 93,
    name: "Luxurious Bronze Bacon",
    price: 879.39,
    image: "https://loremflickr.com/400/300/vegetable?random=93",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 94,
    name: "Elegant Steel Fish",
    price: 58.19,
    image: "https://loremflickr.com/400/300/seed?random=94",
    currency: "₹",
    category: "seed",
  },
  {
    id: 95,
    name: "Luxurious Plastic Ball",
    price: 357.27,
    image: "https://loremflickr.com/400/300/vegetable?random=95",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 96,
    name: "Bespoke Bronze Pizza",
    price: 931.9,
    image: "https://loremflickr.com/400/300/seed?random=96",
    currency: "₹",
    category: "seed",
  },
  {
    id: 97,
    name: "Electronic Steel Cheese",
    price: 773.35,
    image: "https://loremflickr.com/400/300/vegetable?random=97",
    currency: "₹",
    category: "vegetable",
  },
  {
    id: 98,
    name: "Refined Gold Salad",
    price: 719.49,
    image: "https://loremflickr.com/400/300/seed?random=98",
    currency: "₹",
    category: "seed",
  },
  {
    id: 99,
    name: "Frozen Wooden Mouse",
    price: 935.29,
    image: "https://loremflickr.com/400/300/fruit?random=99",
    currency: "₹",
    category: "fruit",
  },
  {
    id: 100,
    name: "Refined Steel Cheese",
    price: 827.69,
    image: "https://loremflickr.com/400/300/vegetable?random=100",
    currency: "₹",
    category: "vegetable",
  },
];
