const products = [
  // 🍎 Fruits (20)
  { id: 1, name: "Apple", price: 5, image: "images/apple.png", currency: "₹", category: "fruit" },
  { id: 2, name: "Banana", price: 2, image: "images/banana.png", currency: "₹", category: "fruit" },
  { id: 3, name: "Orange", price: 4, image: "images/orange.png", currency: "₹", category: "fruit" },
  { id: 4, name: "Mango", price: 12, image: "images/mango.png", currency: "₹", category: "fruit" },
  { id: 5, name: "Strawberry", price: 10, image: "images/strawberry.png", currency: "₹", category: "fruit" },
  { id: 6, name: "Grapes", price: 6, image: "images/grapes.png", currency: "₹", category: "fruit" },
  { id: 7, name: "Pineapple", price: 15, image: "images/pineapple.png", currency: "₹", category: "fruit" },
  { id: 8, name: "Papaya", price: 8, image: "images/papaya.png", currency: "₹", category: "fruit" },
  { id: 9, name: "Watermelon", price: 18, image: "images/watermelon.png", currency: "₹", category: "fruit" },
  { id: 10, name: "Kiwi", price: 9, image: "images/kiwi.png", currency: "₹", category: "fruit" },
  { id: 11, name: "Guava", price: 6, image: "images/guava.png", currency: "₹", category: "fruit" },
  { id: 12, name: "Pear", price: 7, image: "images/pear.png", currency: "₹", category: "fruit" },
  { id: 13, name: "Peach", price: 8, image: "images/peach.png", currency: "₹", category: "fruit" },
  { id: 14, name: "Plum", price: 7, image: "images/plum.png", currency: "₹", category: "fruit" },
  { id: 15, name: "Cherry", price: 14, image: "images/cherry.png", currency: "₹", category: "fruit" },
  { id: 16, name: "Blueberry", price: 16, image: "images/blueberry.png", currency: "₹", category: "fruit" },
  { id: 17, name: "Pomegranate", price: 11, image: "images/pomegranate.png", currency: "₹", category: "fruit" },
  { id: 18, name: "Litchi", price: 13, image: "images/litchi.png", currency: "₹", category: "fruit" },
  { id: 19, name: "Custard Apple", price: 10, image: "images/custard-apple.png", currency: "₹", category: "fruit" },
  { id: 20, name: "Fig", price: 9, image: "images/fig.png", currency: "₹", category: "fruit" },

  // 🥕 Vegetables (20)
  { id: 21, name: "Potato", price: 3, image: "images/potato.png", currency: "₹", category: "vegetable" },
  { id: 22, name: "Tomato", price: 4, image: "images/tomato.png", currency: "₹", category: "vegetable" },
  { id: 23, name: "Onion", price: 3, image: "images/onion.png", currency: "₹", category: "vegetable" },
  { id: 24, name: "Carrot", price: 4, image: "images/carrot.png", currency: "₹", category: "vegetable" },
  { id: 25, name: "Cabbage", price: 5, image: "images/cabbage.png", currency: "₹", category: "vegetable" },
  { id: 26, name: "Cauliflower", price: 6, image: "images/cauliflower.png", currency: "₹", category: "vegetable" },
  { id: 27, name: "Spinach", price: 3, image: "images/spinach.png", currency: "₹", category: "vegetable" },
  { id: 28, name: "Broccoli", price: 7, image: "images/broccoli.png", currency: "₹", category: "vegetable" },
  { id: 29, name: "Green Peas", price: 6, image: "images/green-peas.png", currency: "₹", category: "vegetable" },
  { id: 30, name: "Capsicum", price: 5, image: "images/capsicum.png", currency: "₹", category: "vegetable" },
  { id: 31, name: "Brinjal", price: 4, image: "images/brinjal.png", currency: "₹", category: "vegetable" },
  { id: 32, name: "Pumpkin", price: 8, image: "images/pumpkin.png", currency: "₹", category: "vegetable" },
  { id: 33, name: "Radish", price: 3, image: "images/radish.png", currency: "₹", category: "vegetable" },
  { id: 34, name: "Beetroot", price: 5, image: "images/beetroot.png", currency: "₹", category: "vegetable" },
  { id: 35, name: "Sweet Corn", price: 6, image: "images/sweet-corn.png", currency: "₹", category: "vegetable" },
  { id: 36, name: "Cucumber", price: 4, image: "images/cucumber.png", currency: "₹", category: "vegetable" },
  { id: 37, name: "Bottle Gourd", price: 5, image: "images/bottle-gourd.png", currency: "₹", category: "vegetable" },
  { id: 38, name: "Lady Finger", price: 4, image: "images/lady-finger.png", currency: "₹", category: "vegetable" },
  { id: 39, name: "Mushroom", price: 9, image: "images/mushroom.png", currency: "₹", category: "vegetable" },
  { id: 40, name: "Zucchini", price: 7, image: "images/zucchini.png", currency: "₹", category: "vegetable" },

  // 🌱 Seeds (10)
  { id: 41, name: "Tomato Seeds", price: 15, image: "images/tomato-seeds.png", currency: "₹", category: "seed" },
  { id: 42, name: "Cucumber Seeds", price: 14, image: "images/cucumber-seeds.png", currency: "₹", category: "seed" },
  { id: 43, name: "Chilli Seeds", price: 12, image: "images/chilli-seeds.png", currency: "₹", category: "seed" },
  { id: 44, name: "Pumpkin Seeds", price: 18, image: "images/pumpkin-seeds.png", currency: "₹", category: "seed" },
  { id: 45, name: "Sunflower Seeds", price: 20, image: "images/sunflower-seeds.png", currency: "₹", category: "seed" },
  { id: 46, name: "Watermelon Seeds", price: 16, image: "images/watermelon-seeds.png", currency: "₹", category: "seed" },
  { id: 47, name: "Papaya Seeds", price: 13, image: "images/papaya-seeds.png", currency: "₹", category: "seed" },
  { id: 48, name: "Coriander Seeds", price: 10, image: "images/coriander-seeds.png", currency: "₹", category: "seed" },
  { id: 49, name: "Mustard Seeds", price: 11, image: "images/mustard-seeds.png", currency: "₹", category: "seed" },
  { id: 50, name: "Fenugreek Seeds", price: 9, image: "images/fenugreek-seeds.png", currency: "₹", category: "seed" }
];
